/*
  Copyright 2022 Adobe. All rights reserved.
  This file is licensed to you under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License. You may obtain a copy
  of the License at http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software distributed under
  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
  OF ANY KIND, either express or implied. See the License for the specific language
  governing permissions and limitations under the License.
*/

package com.adobe.marketing.mobile.edge.bridge

import androidx.annotation.VisibleForTesting
import com.adobe.marketing.mobile.Event
import com.adobe.marketing.mobile.EventSource
import com.adobe.marketing.mobile.EventType
import com.adobe.marketing.mobile.Extension
import com.adobe.marketing.mobile.ExtensionApi
import com.adobe.marketing.mobile.services.Log
import com.adobe.marketing.mobile.util.CloneFailedException
import com.adobe.marketing.mobile.util.DataReader
import com.adobe.marketing.mobile.util.EventDataUtils
import com.adobe.marketing.mobile.util.TimeUtils
import java.util.Date

internal class EdgeBridgeExtension(extensionApi: ExtensionApi) : Extension(extensionApi) {

    companion object {
        private const val LOG_SOURCE = "EdgeBridgeExtension"
    }

    override fun getName(): String = EdgeBridgeConstants.EXTENSION_NAME

    override fun getFriendlyName(): String = EdgeBridgeConstants.FRIENDLY_NAME

    override fun getVersion(): String = EdgeBridgeConstants.EXTENSION_VERSION

    override fun onRegistered() {
        api.registerEventListener(
            EventType.GENERIC_TRACK,
            EventSource.REQUEST_CONTENT,
            ::handleTrackRequest
        )
        api.registerEventListener(
            EventType.RULES_ENGINE,
            EventSource.RESPONSE_CONTENT,
            ::handleRulesEngineResponse
        )
    }

    /**
     * Handles generic Analytics track events coming from the public APIs.
     * @param event the generic track request event
     */
    fun handleTrackRequest(event: Event) {
        val eventData = event.eventData

        if (eventData.isNullOrEmpty()) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Unable to handle track request event with id '${event.uniqueIdentifier}': event data is missing or empty."
            )
            return
        }

        dispatchTrackRequest(eventData, event)
    }

    /**
     * Handles Analytics track events generated by a rule consequence.
     * @param event the rules engine response event
     */
    fun handleRulesEngineResponse(event: Event) {
        val eventData = event.eventData

        if (eventData.isNullOrEmpty()) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rules Engine response event with id '${event.uniqueIdentifier}': event data is missing or empty."
            )
            return
        }

        val consequence = DataReader.optTypedMap(
            Any::class.java,
            eventData,
            "triggeredconsequence",
            null
        )

        if (consequence.isNullOrEmpty()) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '${event.uniqueIdentifier}': consequence data is invalid or empty."
            )
            return
        }

        val type = DataReader.optString(consequence, "type", null)

        if (type != "an") {
            return
        }

        val id = DataReader.optString(consequence, "id", null)

        if (id.isNullOrEmpty()) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '${event.uniqueIdentifier}': consequence id is invalid or empty."
            )
            return
        }

        val detail = DataReader.optTypedMap(
            Any::class.java,
            consequence,
            "detail",
            null
        )

        if (detail.isNullOrEmpty()) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '${event.uniqueIdentifier}': consequence detail is invalid or empty."
            )
            return
        }

        dispatchTrackRequest(detail, event)
    }

    /**
     * Helper to create and dispatch an experience event.
     *
     * Track events will not be dispatched in any of the following cases:
     * 1. Deep copy of the event data map fails.
     * 2. Event data map does not have any data or valid action/state.
     *
     * @param data map containing free-form data to send to Edge Network
     * @param parentEvent the triggering parent event used for event chaining; its timestamp is set as xdm.timestamp
     */
    private fun dispatchTrackRequest(data: Map<String, Any>, parentEvent: Event) {
        val formattedData = formatData(data)
        if (formattedData == null) {
            Log.warning(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Event '${parentEvent.uniqueIdentifier}' did not contain any mappable data. Experience event not dispatched."
            )
            return
        }

        val xdmData = mutableMapOf<String, Any>(
            "eventType" to EdgeBridgeConstants.JsonValues.EVENT_TYPE,
            "timestamp" to TimeUtils.getISO8601UTCDateWithMilliseconds(Date(parentEvent.timestamp))
        )

        val eventData = mutableMapOf<String, Any>(
            "xdm" to xdmData,
            "data" to formattedData
        )

        val event = Event.Builder(
            EdgeBridgeConstants.EventNames.EDGE_BRIDGE_REQUEST,
            EventType.EDGE,
            EventSource.REQUEST_CONTENT
        )
            .chainToParentEvent(parentEvent)
            .setEventData(eventData)
            .build()

        api.dispatch(event)
    }

    /**
     * Formats track event data to the required Analytics Edge translator format under the `data.__adobe.analytics` object.
     *
     * The following is the mapping logic:
     * - The "action" field is mapped to "data.__adobe.analytics.linkName", and "data.__adobe.analytics.linkType" is set to "other".
     * - The "state" field is mapped to "data.__adobe.analytics.pageName".
     * - Any "contextData" keys that start with the "&&" prefix are mapped to "data.__adobe.analytics" with the prefix removed.
     * - Any "contextData" keys without the "&&" prefix are mapped to "data.__adobe.analytics.contextData".
     * - Any additional fields are passed through and left directly under the "data" object.
     *
     * As an example, the following track event data:
     * ```
     * {
     *    "action": "action name",
     *    "contextdata": {
     *       "&&c1": "propValue1",
     *       "key1": "value1"
     *    },
     *    "key2": "value2"
     * }
     * ```
     * Is mapped to:
     * ```
     * {
     *   "data": {
     *     "__adobe": {
     *       "analytics": {
     *         "linkName": "action name",
     *         "linkType": "other",
     *         "c1": "propValue1",
     *         "contextData": {
     *           "key1": "value1"
     *         }
     *       }
     *     },
     *     "key2": "value2"
     *   }
     * }
     * ```
     *
     * @param data track event data
     * @return data formatted for the Analytics Edge translator. `null` if there is no data in
     * the payload after format rules are applied, OR if the cloning process fails.
     */
    @VisibleForTesting
    fun formatData(data: Map<String, Any>?): Map<String, Any>? {
        // Create a mutable copy of data - can throw exception if deep copy fails
        val mutableData: MutableMap<String, Any>?
        try {
            mutableData = EventDataUtils.clone(data)
        } catch (e: CloneFailedException) {
            Log.warning(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Failed to format data due to map clone failure: ${e.message}"
            )
            return null
        }

        // If there is no data to format, early exit and return null
        if (mutableData.isNullOrEmpty()) {
            return null
        }

        // __adobe.analytics data container
        val analyticsData = mutableMapOf<String, Any>()

        // Extract contextData
        val extractedContextData = DataReader.optTypedMap(
            Any::class.java,
            mutableData,
            EdgeBridgeConstants.MobileCoreKeys.CONTEXT_DATA,
            null
        )
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.CONTEXT_DATA)

        // Extract action
        val actionValue = DataReader.optString(
            mutableData,
            EdgeBridgeConstants.MobileCoreKeys.ACTION,
            null
        )
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.ACTION)

        // Extract state
        val stateValue = DataReader.optString(
            mutableData,
            EdgeBridgeConstants.MobileCoreKeys.STATE,
            null
        )
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.STATE)

        // Check for required event payload conditions
        // `mutableData` check is still required here because there can be properties outside of the
        // remapped ones that would cause this to still be a valid event
        if (mutableData.isEmpty() && extractedContextData.isNullOrEmpty() &&
            actionValue.isNullOrEmpty() && stateValue.isNullOrEmpty()
        ) {
            return null
        }

        if (!extractedContextData.isNullOrEmpty()) {
            val contextData = cleanContextData(extractedContextData)
            val prefixedData = mutableMapOf<String, Any>()
            val nonPrefixedData = mutableMapOf<String, Any>()

            contextData.forEach { (key, value) ->
                if (key.isNullOrEmpty()) {
                    Log.debug(
                        EdgeBridgeConstants.LOG_TAG,
                        LOG_SOURCE,
                        "formatData - Dropping Key($key) with Value($value). Key must be a non-empty String."
                    )
                    return@forEach
                }

                if (key.startsWith(EdgeBridgeConstants.AnalyticsValues.PREFIX)) {
                    val newKey = key.substring(EdgeBridgeConstants.AnalyticsValues.PREFIX.length)
                    if (newKey.isNullOrEmpty()) {
                        Log.debug(
                            EdgeBridgeConstants.LOG_TAG,
                            LOG_SOURCE,
                            "formatData - Dropping Key($key -> $newKey) with Value($value). Key must be a non-empty String."
                        )
                        return@forEach
                    }
                    prefixedData[newKey] = value
                } else {
                    nonPrefixedData[key] = value
                }
            }

            if (prefixedData.isNotEmpty()) {
                analyticsData.putAll(prefixedData)
            }

            if (nonPrefixedData.isNotEmpty()) {
                analyticsData[EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA] = nonPrefixedData
            }
        }

        // Process action
        if (!actionValue.isNullOrEmpty()) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.LINK_NAME] = actionValue
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.LINK_TYPE] =
                EdgeBridgeConstants.AnalyticsValues.OTHER
        }

        // Process state
        if (!stateValue.isNullOrEmpty()) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.PAGE_NAME] = stateValue
        }

        // If analyticsData is not empty, add it to mutableData under __adobe.analytics
        if (analyticsData.isNotEmpty()) {
            addAnalyticsProperties(analyticsData)
            val adobeAnalytics = mutableMapOf<String, Any>(
                EdgeBridgeConstants.AnalyticsKeys.ANALYTICS to analyticsData
            )
            mutableData[EdgeBridgeConstants.AnalyticsKeys.ADOBE] = adobeAnalytics
        }

        return mutableData
    }

    /**
     * Removes entries with values which cannot be converted to String.
     */
    private fun cleanContextData(eventData: Map<String, Any>): Map<String, String> =
        eventData
            .filterValues { it is String }
            .mapValues { (_, value) -> value as String }

    /**
     * Adds the following keys to the given data map:
     *
     * - `__adobe.analytics.cp`
     * - `__adobe.analytics.contextData.a.AppId`
     *
     * Creates required paths if they are not already present in the original data map.
     * This should be used only after first validating the Analytics data map is valid and should have
     * the additional properties added.
     *
     * @param analyticsData the Analytics data mutable map that will have Analytics properties added.
     */
    @VisibleForTesting
    fun addAnalyticsProperties(analyticsData: MutableMap<String, Any>) {
        // Analytics original implementation: Customer perspective defaults to foreground when unknown
        // and is always present
        analyticsData[EdgeBridgeConstants.AnalyticsKeys.CUSTOMER_PERSPECTIVE] =
            EdgeBridgeProperties.getCustomerPerspective()

        // Analytics original implementation: AppID is only populated if it passes isNullOrEmpty
        // Note that since AppID is the only property dependent on contextData, it being invalid
        // triggers an early exit here; if other metrics are added later, this early exit logic should
        // be updated accordingly.
        val appId = EdgeBridgeProperties.getApplicationIdentifier()
        if (appId.isNullOrEmpty()) {
            return
        }

        // Access to the contextData map
        val contextDataMap: MutableMap<String, Any> = DataReader.optTypedMap(
            Any::class.java,
            analyticsData,
            EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA,
            HashMap()
        )
        if (contextDataMap.isEmpty()) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA] = contextDataMap
        }

        contextDataMap[EdgeBridgeConstants.AnalyticsKeys.APPLICATION_IDENTIFIER] = appId
    }
}
