/*
  Copyright 2022 Adobe. All rights reserved.
  This file is licensed to you under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License. You may obtain a copy
  of the License at http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software distributed under
  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
  OF ANY KIND, either express or implied. See the License for the specific language
  governing permissions and limitations under the License.
*/

package com.adobe.marketing.mobile.edge.bridge

import androidx.annotation.VisibleForTesting
import com.adobe.marketing.mobile.Event
import com.adobe.marketing.mobile.EventSource
import com.adobe.marketing.mobile.EventType
import com.adobe.marketing.mobile.Extension
import com.adobe.marketing.mobile.ExtensionApi
import com.adobe.marketing.mobile.services.Log
import com.adobe.marketing.mobile.util.CloneFailedException
import com.adobe.marketing.mobile.util.DataReader
import com.adobe.marketing.mobile.util.EventDataUtils
import com.adobe.marketing.mobile.util.MapUtils.isNullOrEmpty
import com.adobe.marketing.mobile.util.StringUtils
import com.adobe.marketing.mobile.util.TimeUtils
import java.util.Date

internal class EdgeBridgeExtension(extensionApi: ExtensionApi) : Extension(extensionApi) {

    companion object {
        private const val LOG_SOURCE = "EdgeBridgeExtension"
    }

    public override fun getName(): String = EdgeBridgeConstants.EXTENSION_NAME

    public override fun getFriendlyName(): String = EdgeBridgeConstants.FRIENDLY_NAME

    public override fun getVersion(): String = EdgeBridgeConstants.EXTENSION_VERSION

    public override fun onRegistered() {
        api.registerEventListener(
            EventType.GENERIC_TRACK,
            EventSource.REQUEST_CONTENT,
            ::handleTrackRequest
        )
        api.registerEventListener(
            EventType.RULES_ENGINE,
            EventSource.RESPONSE_CONTENT,
            ::handleRulesEngineResponse
        )
    }

    /**
     * Handles generic Analytics track events coming from the public APIs.
     * @param event the generic track request event
     */
    fun handleTrackRequest(event: Event) {
        val eventData = event.eventData

        if (isNullOrEmpty(eventData)) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Unable to handle track request event with id '%s': event data is missing or empty.",
                event.uniqueIdentifier
            )
            return
        }

        dispatchTrackRequest(eventData, event)
    }

    /**
     * Handles Analytics track events generated by a rule consequence.
     * @param event the rules engine response event
     */
    fun handleRulesEngineResponse(event: Event) {
        val eventData = event.eventData

        if (isNullOrEmpty(eventData)) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rules Engine response event with id '%s': event data is missing or empty.",
                event.uniqueIdentifier
            )
            return
        }

        val consequence = DataReader.optTypedMap(
            Any::class.java,
            eventData,
            "triggeredconsequence",
            null
        )

        if (isNullOrEmpty(consequence)) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '%s': consequence data is invalid or empty.",
                event.uniqueIdentifier
            )
            return
        }

        val type = DataReader.optString(consequence, "type", null)

        if ("an" != type) {
            return
        }

        val id = DataReader.optString(consequence, "id", null)

        if (StringUtils.isNullOrEmpty(id)) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '%s': consequence id is invalid or empty.",
                event.uniqueIdentifier
            )
            return
        }

        val detail = DataReader.optTypedMap(Any::class.java, consequence, "detail", null)

        if (isNullOrEmpty(detail)) {
            Log.trace(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Ignoring Rule Engine response event with id '%s': consequence detail is invalid or empty.",
                event.uniqueIdentifier
            )
            return
        }

        dispatchTrackRequest(detail, event)
    }

    /**
     * Helper to create and dispatch an experience event.
     *
     * Track events will not be dispatched in any of the following cases:
     * 1. Deep copy of the event data map fails.
     * 2. Event data map does not have any data or valid action/state.
     *
     * @param data map containing free-form data to send to Edge Network
     * @param parentEvent the triggering parent event used for event chaining; its timestamp is set as xdm.timestamp
     */
    private fun dispatchTrackRequest(data: Map<String, Any>, parentEvent: Event) {
        val formattedData = formatData(data)
        if (formattedData == null) {
            Log.warning(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Event '${parentEvent.uniqueIdentifier}' did not contain any mappable data. Experience event not dispatched."
            )
            return
        }

        val xdmData = HashMap<String, Any>()
        xdmData["eventType"] = EdgeBridgeConstants.JsonValues.EVENT_TYPE
        xdmData["timestamp"] = TimeUtils.getISO8601UTCDateWithMilliseconds(Date(parentEvent.timestamp))

        val eventData = HashMap<String, Any>()
        eventData["xdm"] = xdmData
        eventData["data"] = formattedData

        val event = Event.Builder(
            EdgeBridgeConstants.EventNames.EDGE_BRIDGE_REQUEST,
            EventType.EDGE,
            EventSource.REQUEST_CONTENT
        )
            .chainToParentEvent(parentEvent)
            .setEventData(eventData)
            .build()

        api.dispatch(event)
    }

    /**
     * Formats track event data to the required Analytics Edge translator format under the
     * `data.__adobe.analytics` object.
     *
     * The following is the mapping logic:
     * - The "action" field is mapped to "data.__adobe.analytics.linkName", and
     *   "data.__adobe.analytics.linkType" is set to "other".
     * - The "state" field is mapped to "data.__adobe.analytics.pageName".
     * - Any "contextData" keys that start with the "&&" prefix are mapped to
     *   "data.__adobe.analytics" with the prefix removed.
     * - Any "contextData" keys without the "&&" prefix are mapped to
     *   "data.__adobe.analytics.contextData".
     * - Any additional fields are passed through and left directly under the "data" object.
     *
     * @param data track event data
     * @return data formatted for the Analytics Edge translator. `null` if there is no data in
     * the payload after format rules are applied, OR if the cloning process fails.
     */
    @VisibleForTesting
    fun formatData(data: Map<String, Any>?): Map<String, Any>? {
        val mutableData: MutableMap<String, Any>
        try {
            val cloned: MutableMap<String, Any>? = EventDataUtils.clone(data)
            if (isNullOrEmpty(cloned)) {
                return null
            }
            mutableData = cloned!!
        } catch (e: CloneFailedException) {
            Log.warning(
                EdgeBridgeConstants.LOG_TAG,
                LOG_SOURCE,
                "Failed to format data due to map clone failure: ${e.message}"
            )
            return null
        }

        val analyticsData = HashMap<String, Any>()

        val extractedContextData = DataReader.optTypedMap(
            Any::class.java,
            mutableData,
            EdgeBridgeConstants.MobileCoreKeys.CONTEXT_DATA,
            null
        )
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.CONTEXT_DATA)

        val actionValue = DataReader.optString(mutableData, EdgeBridgeConstants.MobileCoreKeys.ACTION, null)
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.ACTION)
        val stateValue = DataReader.optString(mutableData, EdgeBridgeConstants.MobileCoreKeys.STATE, null)
        mutableData.remove(EdgeBridgeConstants.MobileCoreKeys.STATE)

        val actionIsValid = !StringUtils.isNullOrEmpty(actionValue)
        val stateIsValid = !StringUtils.isNullOrEmpty(stateValue)

        if (isNullOrEmpty(mutableData) && isNullOrEmpty(extractedContextData) && !actionIsValid && !stateIsValid) {
            return null
        }

        if (!isNullOrEmpty(extractedContextData)) {
            val contextData = cleanContextData(extractedContextData)
            val prefixedData = HashMap<String, Any>()
            val nonPrefixedData = HashMap<String, Any>()

            for ((key, value) in contextData) {
                if (StringUtils.isNullOrEmpty(key)) {
                    Log.debug(
                        EdgeBridgeConstants.LOG_TAG,
                        LOG_SOURCE,
                        "formatData - Dropping Key($key) with Value($value). Key must be a non-empty String."
                    )
                    continue
                }

                if (key.startsWith(EdgeBridgeConstants.AnalyticsValues.PREFIX)) {
                    val newKey = key.substring(EdgeBridgeConstants.AnalyticsValues.PREFIX.length)
                    if (StringUtils.isNullOrEmpty(newKey)) {
                        Log.debug(
                            EdgeBridgeConstants.LOG_TAG,
                            LOG_SOURCE,
                            "formatData - Dropping Key($key -> $newKey) with Value($value). Key must be a non-empty String."
                        )
                        continue
                    }
                    prefixedData[newKey] = value
                } else {
                    nonPrefixedData[key] = value
                }
            }

            if (prefixedData.isNotEmpty()) {
                analyticsData.putAll(prefixedData)
            }

            if (nonPrefixedData.isNotEmpty()) {
                analyticsData[EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA] = nonPrefixedData
            }
        }

        if (actionIsValid) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.LINK_NAME] = actionValue as Any
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.LINK_TYPE] = EdgeBridgeConstants.AnalyticsValues.OTHER
        }

        if (stateIsValid) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.PAGE_NAME] = stateValue as Any
        }

        if (analyticsData.isNotEmpty()) {
            addAnalyticsProperties(analyticsData)
            val adobeAnalytics = HashMap<String, Any>()
            adobeAnalytics[EdgeBridgeConstants.AnalyticsKeys.ANALYTICS] = analyticsData
            mutableData[EdgeBridgeConstants.AnalyticsKeys.ADOBE] = adobeAnalytics
        }

        return mutableData
    }

    /**
     * Remove entries with values which cannot be converted to String.
     */
    private fun cleanContextData(eventData: Map<String, Any>): Map<String, String> {
        val cleanedData = HashMap<String, String>()
        for ((key, value) in eventData) {
            if (value is String) {
                cleanedData[key] = value
            }
        }
        return cleanedData
    }

    /**
     * Adds the following keys to the given data map:
     *
     * `__adobe.analytics.cp`
     *
     * `__adobe.analytics.contextData.a.AppId`
     *
     * Creates required paths if they are not already present in the original data map.
     * This should be used only after first validating the Analytics data map is valid and should have
     * the additional properties added.
     *
     * @param analyticsData the Analytics data mutable map that will have Analytics properties added.
     */
    @VisibleForTesting
    fun addAnalyticsProperties(analyticsData: MutableMap<String, Any>) {
        analyticsData[EdgeBridgeConstants.AnalyticsKeys.CUSTOMER_PERSPECTIVE] =
            EdgeBridgeProperties.getCustomerPerspective()

        val appId = EdgeBridgeProperties.getApplicationIdentifier()
        if (StringUtils.isNullOrEmpty(appId)) {
            return
        }

        val contextDataMap = DataReader.optTypedMap(
            Any::class.java,
            analyticsData,
            EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA,
            HashMap()
        )
        if (contextDataMap.isEmpty()) {
            analyticsData[EdgeBridgeConstants.AnalyticsKeys.CONTEXT_DATA] = contextDataMap
        }

        contextDataMap[EdgeBridgeConstants.AnalyticsKeys.APPLICATION_IDENTIFIER] = appId
    }
}
